name: Server smoke test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  run-server:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask authlib sqlalchemy

      - name: Start server
        run: |
          nohup python server.py > server.log 2>&1 &
          echo $! > server.pid

      - name: Wait for health
        run: |
          for i in {1..40}; do
            if curl -fsS http://127.0.0.1:8000/health >/dev/null; then
              echo "Server is healthy"; exit 0; fi
            sleep 1; done
          echo "Server failed to become healthy"; exit 1

      - name: Show last server logs (on failure)
        if: failure()
        run: |
          echo '--- server.log (tail) ---'
          tail -n 200 server.log || true

      - name: Shutdown server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
          sleep 1
          echo '--- server.log (tail after shutdown) ---'
          tail -n 200 server.log || true
